// Copies pinned, minified ES module builds of the page's libraries into /work/vendor.
// The page loads them through an import map, so there is no build step at deploy time.
// Re-run after changing a version in package.json:  npm run vendor
import { build } from 'esbuild';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const out = fileURLToPath(new URL('../vendor/', import.meta.url));
mkdirSync(out, { recursive: true });

const pkg = (name) => JSON.parse(readFileSync(new URL(`./node_modules/${name}/package.json`, import.meta.url))).version;
const threeExternal = {
  name: 'three-external',
  setup(b) { b.onResolve({ filter: /^three$/ }, () => ({ path: 'three', external: true })); },
};
const banner = (name) => ({ js: `/* ${name}@${pkg(name)} | vendored for /work/ */` });

// three core: one self-contained file.
await build({
  entryPoints: ['three'],
  bundle: true, minify: true, format: 'esm', target: 'es2020',
  outfile: out + 'three.module.min.js', banner: banner('three'), logLevel: 'warning',
});

// Only the addons the page imports. Paths are file paths so that only the bare `three`
// import stays external (resolved by the import map); esbuild would otherwise treat
// every `three/...` subpath as external too.
const addons = `
export { GLTFLoader } from './node_modules/three/examples/jsm/loaders/GLTFLoader.js';
export { RoomEnvironment } from './node_modules/three/examples/jsm/environments/RoomEnvironment.js';
export { MeshoptDecoder } from './node_modules/three/examples/jsm/libs/meshopt_decoder.module.js';
`;
await build({
  stdin: { contents: addons, resolveDir: fileURLToPath(new URL('.', import.meta.url)), loader: 'js' },
  bundle: true, minify: true, format: 'esm', target: 'es2020', plugins: [threeExternal],
  outfile: out + 'three-addons.min.js', banner: banner('three'), logLevel: 'warning',
});

await build({
  entryPoints: ['lenis'],
  bundle: true, minify: true, format: 'esm', target: 'es2020',
  outfile: out + 'lenis.min.js', banner: banner('lenis'), logLevel: 'warning',
});

writeFileSync(out + 'VERSIONS.txt', `three ${pkg('three')}\nlenis ${pkg('lenis')}\nGenerated by work/tools/vendor.mjs\n`);
console.log('vendored into', out);
